package com.quehacerenzaragoza.soydezaragoza.util.extensions

const val BASE_URL = "https://soydezaragoza.es/"
const val POSTS_END_POINT = "wp/v2/posts"
const val POST_REVISIONS_END_POINT = "wp/v2/posts/{id}/revisions"
const val CATEGORIES_END_POINT = "wp/v2/categories"
const val TAGS_END_POINT = "wp/v2/tags"
const val PAGES_END_POINT = "wp/v2/pages"
const val PAGE_REVISIONS_END_POINT = "wp/v2/pages/{id}/revisions"
const val COMMENTS_END_POINT = "wp/v2/comments"
const val TAXONOMIES_END_POINT = "wp/v2/taxonomies"
const val MEDIA_END_POINT = "wp/v2/media"
const val USERS_END_POINT = "wp/v2/users"
const val POST_TYPES_END_POINT = "wp/v2/types"
const val POST_STATUSES_END_POINT = "wp/v2/statuses"
const val SETTINGS_END_POINT = "wp/v2/settings"
const val THEMES_END_POINT = "wp/v2/themes"
const val SEARCH_END_POINT = "wp/v2/search"
const val BLOCK_TYPES_END_POINT = "wp/v2/block-types"
const val BLOCKS_END_POINT = "wp/v2/blocks"
const val BLOCK_REVISIONS_END_POINT = "wp/v2/blocks/{id}/autosaves"
const val BLOCK_RENDERER_END_POINT = "wp/v2/block-renderer"
const val BLOCK_DIRECTORY_ITEMS_END_POINT = "wp/v2/block-directory/search"
const val PLUGINS_END_POINT = "wp/v2/plugins"
